name: join_availability_group
description: join database to SQL availability group

inputs:
  name-prefix:
    description: 'Name prefix'
    required: false
    default: ''
  pd-number:
    description: 'PD number'
    required: false
    default: ''
  full-domain-name:
    description: 'Full domain name'
    required: true
  ag-name:
    description: 'Name of the availability group'
    required: true
  server-hostname:
    description: 'Hostname of the server'
    required: true
  instance:
    required: true

runs:
  using: "composite"
  steps:
    - name: Invoke SQL join AG
      run: >
        Invoke-Sqlcmd -TrustServerCertificate -InputFile .\scripts\PD\Join-to-AG.sql
        -ServerInstance ${{ inputs.name-prefix }}${{ inputs.pd-number }}${{ inputs.server-hostname }}.${{ inputs.full-domain-name }}\${{ inputs.name-prefix }}${{ inputs.pd-number }}${{ inputs.instance }}
        -V 'AGname=${{ inputs.name-prefix }}${{ inputs.pd-number }}-${{ inputs.ag-name }}'
      shell: powershell
      working-directory: ./github-runner
