name: spn_settings_exa
description: Sets the SPN settings for EXA

inputs:
  pd-number:
    description: 'PD number'
    required: false
    default: '1'
  full-domain-name:
    description: 'Full domain name'
    required: true
  sql-user:
    description: 'SQL user'
    required: true
  name-prefix:
    description: 'Name prefix'
    required: false

runs:
  using: "composite"
  steps:
    - name: Add SPN to AD
      run: >
        .\scripts\CCMH\spn-add.ps1
        -sqlserviceaccount "${{ inputs.sql-user }}"
        -fullDomain "${{ inputs.full-domain-name }}"
        -prefix "${{ inputs.name-prefix }}${{ inputs.pd-number }}"
      shell: powershell
      working-directory: ./github-runner
