USE [master]
GO
CREATE LOGIN [NETBIOSNAME\dd-agent-user$] FROM WINDOWS WITH DEFAULT_DATABASE=[master]
GO
CREATE USER datadog FOR LOGIN [NETBIOSNAME\dd-agent-user$];
go
GRANT CONNECT ANY DATABASE to [NETBIOSNAME\dd-agent-user$] ;
GRANT VIEW SERVER STATE to [NETBIOSNAME\dd-agent-user$] ;
GRANT VIEW ANY DEFINITION to [NETBIOSNAME\dd-agent-user$] ;
