name: agentjob_dboperator
description: Runs the update agent job settings, add db operator

inputs:
  name-prefix:
    description: 'Name prefix'
    required: false
    default: ''
  pd-number:
    description: 'PD number'
    required: false
    default: ''
  full-domain-name:
    description: 'Full domain name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Invoke script UpdateAgentJobOwner
      run: >
        .\scripts\CCMH\UpdateAgentJobOwner.ps1
        -PrimaryServer "${{ inputs.name-prefix }}${{ inputs.pd-number }}DBS01.${{ inputs.full-domain-name }}\${{ inputs.name-prefix }}${{ inputs.pd-number }}DB"
        -SecondaryServer "${{ inputs.name-prefix }}${{ inputs.pd-number }}DBS02.${{ inputs.full-domain-name }}\${{ inputs.name-prefix }}${{ inputs.pd-number }}DB"
      shell: powershell
      working-directory: ./github-runner

    - name: Invoke script CreateDBOperator
      run: >
        .\scripts\CCMH\CreateDBOperator.ps1
        -PrimaryServer "${{ inputs.name-prefix }}${{ inputs.pd-number }}DBS01.${{ inputs.full-domain-name }}\${{ inputs.name-prefix }}${{ inputs.pd-number }}DB"
        -SecondaryServer "${{ inputs.name-prefix }}${{ inputs.pd-number }}DBS02.${{ inputs.full-domain-name }}\${{ inputs.name-prefix }}${{ inputs.pd-number }}DB"
      shell: powershell
      working-directory: ./github-runner
