name: DEV - DESTROY - Infrastructure
on: 
  workflow_dispatch:
    inputs:
      DESTROY:
        description: 'Resources to DESTROY'
        required: true
        type: choice
        options:
          - ec2
          - network
          - network-addons

concurrency: dev-destroy

permissions:
  id-token: write
  contents: read

env:
  ssh_key: ${{ secrets.ssh_key }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  DEPLOYER_ROLE_ARN: ${{ secrets.DEPLOYER_ROLE_ARN }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  ENVIRONMENT: ${{ vars.ENVIRONMENT }}
  DOMAIN_CREDENTIALS: ${{ secrets.DOMAIN_CREDENTIALS }}
  FULL_DOMAIN_NAME: ${{ secrets.FULL_DOMAIN_NAME }}

jobs:
  plan-destroy:
    name: Pull Request - Lint & Plan - DEV ${{ github.event.inputs.DESTROY }}
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DEPLOYER_ROLE_ARN }}
          role-session-name: deploy-role-session
          aws-region: ${{ vars.AWS_REGION }}

      - uses: navikt/github-app-token-generator@v1
        id: get-token
        with:
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          app-id: ${{ secrets.APP_ID }}

      - name: Pull & update submodules recursively
        run: |
          git config --global url.https://token:${{ steps.get-token.outputs.token }}@github.com/emisgroup.insteadOf https://github.com/emisgroup
          git config --file=.gitmodules github-runner.url https://token:${{ steps.get-token.outputs.token }}@github.com/emisgroup/github-runner.git
          git submodule update --init --recursive
        env:
          GI_TOKEN: ${{ steps.get-token.outputs.token }}

      - name: Run Checkov
        if: github.event.inputs.DESTROY == 'ec2'
        uses: bridgecrewio/checkov-action@master
        with:
          directory: eweblogs/terraform
          framework: terraform

      - name: Plan Destroy EC2
        if: github.event.inputs.DESTROY == 'ec2'
        env:
          GI_TOKEN: ${{ steps.get-token.outputs.token }}
        uses: ./github-runner/actions/terragrunt-plan-destroy
        with:
          terraform-folder: "../eweblogs/terraform"
          terragrunt-config: "../terragrunt.hcl"
  


      - name: Run Checkov - Addons
        if: github.event.inputs.DESTROY == 'network-addons'
        uses: bridgecrewio/checkov-action@master
        with:
          directory: eweblogs/terraform/addons
          framework: terraform

      - name: Plan Destroy Addons
        if: github.event.inputs.DESTROY == 'network-addons'
        env:
          GI_TOKEN: ${{ steps.get-token.outputs.token }}
        uses: ./github-runner/actions/terragrunt-plan-destroy
        with:
          terraform-folder: "../eweblogs/terraform/addons"
          terragrunt-config: "./terragrunt.hcl"



      - name: Run Checkov - Network
        if: github.event.inputs.DESTROY == 'network'
        uses: bridgecrewio/checkov-action@master
        with:
          directory: eweblogs/terraform/network
          framework: terraform
      
      - name: Plan Destroy Network
        if: github.event.inputs.DESTROY == 'network'
        env:
          GI_TOKEN: ${{ steps.get-token.outputs.token }}
        uses: ./github-runner/actions/terragrunt-plan-destroy
        with:
          terraform-folder: "../eweblogs/terraform/network"
          terragrunt-config: "./terragrunt.hcl"


  destroy:
    name: Destroy - DEV Infrastructure
    if: github.ref == 'refs/heads/develop'
    needs: plan-destroy
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DEPLOYER_ROLE_ARN }}
          role-session-name: deploy-role-session
          aws-region: ${{ vars.AWS_REGION }}

      - uses: navikt/github-app-token-generator@v1
        id: get-token
        with:
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          app-id: ${{ secrets.APP_ID }}

      - name: Pull & update submodules recursively
        run: |
          git config --global url.https://token:${{ steps.get-token.outputs.token }}@github.com/emisgroup.insteadOf https://github.com/emisgroup
          git config --file=.gitmodules github-runner.url https://token:${{ steps.get-token.outputs.token }}@github.com/emisgroup/github-runner.git
          git submodule update --init --recursive
        env:
          GI_TOKEN: ${{ steps.get-token.outputs.token }}


      - name: Destroy EC2
        if: github.event.inputs.DESTROY == 'ec2'
        env:
          GI_TOKEN: ${{ steps.get-token.outputs.token }}
        uses: ./github-runner/actions/terragrunt-destroy
        with:
          terraform-folder: "../eweblogs/terraform"
          terragrunt-config: "../terragrunt.hcl"

      - name: Destroy Addons
        if: github.event.inputs.DESTROY == 'network-addons'
        env:
          GI_TOKEN: ${{ steps.get-token.outputs.token }}
        uses: ./github-runner/actions/terragrunt-destroy
        with:
          terraform-folder: "../eweblogs/terraform/addons"
          terragrunt-config: "./terragrunt.hcl"

      - name: Destroy Network
        if: github.event.inputs.DESTROY == 'network'
        env:
          GI_TOKEN: ${{ steps.get-token.outputs.token }}
        uses: ./github-runner/actions/terragrunt-destroy
        with:
          terraform-folder: "../eweblogs/terraform/network"
          terragrunt-config: "./terragrunt.hcl"
