name: rename_nic
description: Action to rename network interfaces for a target host

inputs:
  pd-number:
    description: 'PD number'
    required: true
  name-prefix:
    description: 'Name prefix'
    required: true
  full-domain-name:
    description: 'Full domain name'
    required: true
  server-hostname:
    description: 'Server hostname'
    required: true

runs:
  using: "composite"
  steps:
    - name:
      run: |
        Invoke-Command -ScriptBlock {
          Rename-NetAdapter -Name "Ethernet*" -NewName "Private"
        } -ComputerName ${{ inputs.name-prefix }}${{ inputs.pd-number }}${{ inputs.server-hostname }}.${{ inputs.full-domain-name }}
      shell: powershell
