name: Map instances to AD Group
description: Map the computer AD objects to the computer group in AD

inputs:
  name-prefix:
    description: 'Name prefix'
    required: true
  pd-number:
    description: 'PD number'
    required: true
  full-domain-name:
    description: 'Full domain name'
    required: true

runs:
  using: "composite"
  steps:
    - name: "Map DBS01"
      run: >
        .\scripts\PD\MapInstanceToGroupsAD.ps1
        -pdNumber "${{ inputs.pd-number }}"
        -InstanceHostname "${{ inputs.name-prefix }}${{ inputs.pd-number }}DBS01"
      shell: powershell
      working-directory: ./github-runner

    - name: "Map DBS02"
      run: >
        .\scripts\PD\MapInstanceToGroupsAD.ps1
        -pdNumber "${{ inputs.pd-number }}"
        -InstanceHostname "${{ inputs.name-prefix }}${{ inputs.pd-number }}DBS02"
      shell: powershell
      working-directory: ./github-runner

    - name: "Local admins DBS01"
      run: >
        Invoke-Command -FilePath .\scripts\PD\AddLocalAdmins.ps1
        -ComputerName ${{ inputs.name-prefix }}${{ inputs.pd-number }}DBS01.${{ inputs.full-domain-name }}
        -ArgumentList "${{ inputs.pd-number }}"
      shell: powershell
      working-directory: ./github-runner

    - name: "Local admins DBS02"
      run: >
        Invoke-Command -FilePath .\scripts\PD\AddLocalAdmins.ps1
        -ComputerName ${{ inputs.name-prefix }}${{ inputs.pd-number }}DBS02.${{ inputs.full-domain-name }}
        -ArgumentList "${{ inputs.pd-number }}"
      shell: powershell
      working-directory: ./github-runner

    - name: "Create folders DBS01"
      run: >
        Invoke-Command -FilePath .\scripts\CCMH\CreateFolders.ps1
        -ComputerName ${{ inputs.name-prefix }}${{ inputs.pd-number }}DBS01.${{ inputs.full-domain-name }}
      shell: powershell
      working-directory: ./github-runner

    - name: "Create folders DBS02"
      run: >
        Invoke-Command -FilePath .\scripts\CCMH\CreateFolders.ps1
        -ComputerName ${{ inputs.name-prefix }}${{ inputs.pd-number }}DBS02.${{ inputs.full-domain-name }}
      shell: powershell
      working-directory: ./github-runner
