name: Map instances to AD Group
description: Map the computer AD objects to the computer group in AD

inputs:
  name-prefix:
    description: 'Name prefix'
    required: true
  pd-number:
    description: 'PD number'
    required: true
  full-domain-name:
    description: 'Full domain name'
    required: true
  server-hostname:
    description: 'Instance hostname'
    required: true

runs:
  using: "composite"
  steps:
    - name: "Map Instance"
      run: >
        .\scripts\PD\MapCLSAGInstancestoGroups.ps1
        -InstanceHostname "${{ inputs.name-prefix }}${{ inputs.pd-number }}${{ inputs.server-hostname }}"
      shell: powershell
      working-directory: ./github-runner
