name: copy_sql_installers
description: Action to copy sql installers from s3 bucket

inputs:
  pd-number:
    description: 'PD number'
    required: true
  setup-bucket-name:
    description: 'S3 bucket with installers in'
    required: true
  name-prefix:
    description: 'Name prefix'
    required: true
  name-suffix:
    description: 'Name suffix'
    required: true
  full-domain-name:
    description: 'Full domain name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Copy installer files from S3
      run: >
        Invoke-Command -FilePath .\scripts\CCMHUAT\CopySqlInstallers.ps1
        -ComputerName ${{ inputs.name-prefix }}${{ inputs.pd-number }}${{ inputs.name-suffix }}.${{ inputs.full-domain-name }}
        -ArgumentList "${{ inputs.setup-bucket-name }}", "SQL-Installers"
      shell: powershell
      working-directory: ./github-runner
