name: Login_as_service_configuration
description: grant service account login as service rights

inputs:
  name-prefix:
    description: 'Name prefix'
    required: false
    default: ''
  pd-number:
    description: 'PD number'
    required: false
    default: ''
  full-domain-name:
    description: 'Full domain name'
    required: true
  authdbaccess-user:
    description: 'Authentication Database User'
    required: true
  server-hostname:
    description: 'Server hostname'
    required: true
  netbios-name:
    description: 'netbios name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Invoke grant SDS service account login as service rights
      run: >
        .\scripts\PD\grant-SeServiceLogonRight.ps1
        -computerName ${{ inputs.name-prefix }}${{ inputs.pd-number }}${{ inputs.server-hostname }}.${{ inputs.full-domain-name }}
        -username "${{ inputs.netbios-name }}\${{ inputs.authdbaccess-user }}$"
      shell: powershell
      working-directory: ./github-runner