name: restore_db
description: Action to restore the DBs from a backup

inputs:
  pd-number:
    description: 'PD number'
    required: true
  setup-bucket-name:
    description: 'S3 bucket with DB backups in'
    required: true
  name-prefix:
    description: 'Name prefix'
    required: true
  name-suffix:
    description: 'Name suffix'
    required: true
  full-domain-name:
    description: 'Full domain name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Copy backup files from S3
      run: >
        Invoke-Command -FilePath .\scripts\CCMHUAT\RestoreDB-CopyBackupFiles.ps1
        -ComputerName ${{ inputs.name-prefix }}${{ inputs.pd-number }}${{ inputs.name-suffix }}.${{ inputs.full-domain-name }}
        -ArgumentList "${{ inputs.setup-bucket-name }}", "DBA"
      shell: powershell
      working-directory: ./github-runner
    - name: Restore DBs
      run: |
        $primarySqlServer = "${{ inputs.name-prefix }}${{ inputs.pd-number }}${{ inputs.name-suffix }}.${{ inputs.full-domain-name }}\${{ inputs.name-prefix }}${{ inputs.pd-number }}${{ inputs.name-suffix }}"
        .\scripts\CCMHUAT\RestoreDB2-Restore.ps1 `
        -primarySqlServer $primarySqlServer `
        -s3Path "DBA" `
        -pdNumber ${{ inputs.pd-number }}
      shell: powershell
      working-directory: ./github-runner
