# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "dev-eweblogs-plat-s3-terraform-state-296062593024"
    dynamodb_table = "dev-eweblogs-plat-s3-terraform-locks-296062593024"
    encrypt        = true
    key            = "network/dev-eweblogs.tfstate"
    region         = "eu-west-2"
  }
}
