# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
    }
    github = {
      source  = "integrations/github"
      version = "~> 4.0"
    }
  }
}
provider "aws" {
  region = "eu-west-2"
  allowed_account_ids = [
    "296062593024",
  ]
  default_tags {
    tags = {
      environment      = "dev"
      service          = "eweb"
      owner            = "hosted-platforms"
      business_unit    = "primary-care"
      product          = "emis-web"
      service_location = "england"
      account_state    = "0"
      programme_name   = "adelaide"
      project_name     = "brisbane"
      project_code     = "prj0011476"
      iac_source       = "terraform"
      dr               = "mission_critical"
      BackupClass      = "platinum"
    }
  }
}
provider "github" {}
