name: create-cluster
description: run the create cluster script

inputs:
  cluster-name:
    description: 'SQL server cluster name'
    required: true
  name-prefix:
    description: 'Name prefix'
    required: false
    default: ''
  pd-number:
    description: 'PD number'
    required: false
    default: ''
  full-domain-name:
    description: 'Full domain name'
    required: true
  primary-cluster-ip:
    description: 'Static IP of the primary node in the cluster'
    required: true
  secondary-cluster-ip:
    description: 'Static IP of the secondary node in the cluster'
    required: true
  rs-cluster-ip:
    description: 'Static IP of the replica node in the cluster'
    required: true
  admin-secret-arn:
    description: 'Directory Admin secret arn'
    required: true

runs:
  using: "composite"
  steps:
    - name: create-cluster-command
      run: >
        .\scripts\Nations\CreateCluster_rs.ps1
        -node1 ${{ inputs.name-prefix }}${{ inputs.pd-number }}DBS01.${{ inputs.full-domain-name }}
        -node2 ${{ inputs.name-prefix }}${{ inputs.pd-number }}DBS02.${{ inputs.full-domain-name }}
        -node3 ${{ inputs.name-prefix }}${{ inputs.pd-number }}RS-01.${{ inputs.full-domain-name }}
        -clusterName ${{ inputs.cluster-name }}
        -domainName ${{ inputs.full-domain-name }}
        -primaryClusterIp ${{ inputs.primary-cluster-ip }}
        -secondaryClusterIp ${{ inputs.secondary-cluster-ip }}
        -replicaClusterIp ${{ inputs.rs-cluster-ip }}
        -SecretArn ${{ inputs.admin-secret-arn }}
      shell: powershell
      working-directory: ./github-runner