name: install_wsus
description: Install windows updates

inputs:
  server-name:
    description: 'Instance name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install windows updates
      run: |
        echo "Installing windows updates."
        instanceId=$(aws ec2 describe-instances --filters 'Name=tag:Name,Values=${{ inputs.server-name }}' 'Name=instance-state-name,Values=running' --query 'Reservations[].Instances[].[InstanceId]' --output text)
        commandId=$(aws ssm send-command --instance-ids $instanceId --document-name "EMIS-WSUSInstallUpdates" --query 'Command.CommandId' --output text)

        # wait for EMIS-WSUSInstallUpdates SSM run command to complete
        command_status="starting"
        while [ $command_status != "Success" ]
        do
          echo "wsus config still running"
          sleep 10
          command_status=$(aws ssm get-command-invocation --command-id $commandId --instance-id $instanceId --query 'Status' --output text)
          if [ $command_status = "Failed" ]
          then
            echo "wsus config failed"
            aws ssm list-command-invocations --command-id $commandId --details --query "CommandInvocations[*].CommandPlugins[*].Output[]" --output text
            exit 1
          fi
        done
        echo "wsus config complete"
        aws ssm list-command-invocations --command-id $commandId --details --query "CommandInvocations[*].CommandPlugins[*].Output[]" --output text
      shell: bash
      working-directory: ./github-runner
