name: pd_ad_update
description: Action to create the organisational unit, ad users and groups with powershell scripts

inputs:
  pd-number:
    description: 'PD number'
    required: true
  default-secret-name:
    description: 'Default secret name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Invoke script createOU
      run: >
         .\scripts\PD\CreateOU.ps1 -pdNumber ${{ inputs.pd-number }} `
         -DefaultSecretName ${{ inputs.default-secret-name }}
      shell: powershell
      working-directory: ./github-runner

    - name: Invoke script CreateADUserGroups
      run: >
         .\scripts\PD\CreateADUserGroups.ps1 -pdNumber ${{ inputs.pd-number }} `
         -DefaultSecretName ${{ inputs.default-secret-name }}
      shell: powershell
      working-directory: ./github-runner

    - name: Invoke script CreateADUsers
      run: >
         .\scripts\PD\CreateADUsers.ps1 -pdNumber ${{ inputs.pd-number }} `
         -DefaultSecretName ${{ inputs.default-secret-name }}
      shell: powershell
      working-directory: ./github-runner

    - name: Invoke script MapADUserGroups
      run: >
         .\scripts\PD\MapADUserGroups.ps1 -pdNumber ${{ inputs.pd-number }} `
         -DefaultSecretName ${{ inputs.default-secret-name }}
      shell: powershell
      working-directory: ./github-runner

    - name: Invoke script LinkOUGPO
      run: >
         .\scripts\PD\LinkOUGPO.ps1 -pdNumber ${{ inputs.pd-number }} `
         -DefaultSecretName ${{ inputs.default-secret-name }}
      shell: powershell
      working-directory: ./github-runner
