name: create_ad_runner
description: Creates a self hosted runner for AD workflows

inputs:
  gh-token:
    description: 'gh token to create runners'
    required: true
  secret-id:
    description: 'Directory Admin secret arn'
    required: true

runs:
  using: "composite"
  steps:
    - name: Invoke script to create temp ad runner
      run: >
         .\scripts\setup_temp_ad_runner.ps1 -GH_TOKEN ${{ inputs.gh-token }} -secretId ${{ inputs.secret-id }}
      shell: powershell
      working-directory: ./eweblogs
    - name: Wait 30 minutes
      run: >
         start-sleep -Seconds 1800
      shell: powershell
      working-directory: ./eweblogs
    - name: Invoke script to delete temp ad runner
      run: >
         .\scripts\delete_temp_ad_runner.ps1 -GH_TOKEN ${{ inputs.gh-token }} -secretId ${{ inputs.secret-id }}
      shell: powershell
      working-directory: ./eweblogs