name: DEV - Destroy - Infrastructure
on: workflow_dispatch

concurrency: dev

permissions:
  id-token: write
  contents: read

env:
  ssh_key: ${{ secrets.ssh_key }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  DEPLOYER_ROLE_ARN: ${{ secrets.DEPLOYER_ROLE_ARN }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  ENVIRONMENT: ${{ vars.ENVIRONMENT }}
  DOMAIN_CREDENTIALS: ${{ secrets.DOMAIN_CREDENTIALS }}

jobs:
  destroy:
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/develop'
    environment:
      name: dev
    name: Destroy - DEV Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DEPLOYER_ROLE_ARN }}
          role-session-name: deploy-role-session
          aws-region: ${{ vars.AWS_REGION }}

      - uses: navikt/github-app-token-generator@v1
        id: get-token
        with:
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          app-id: ${{ secrets.APP_ID }}

      - name: Pull & update submodules recursively
        run: |
          git config --global url.https://token:${{ steps.get-token.outputs.token }}@github.com/emisgroup.insteadOf https://github.com/emisgroup
          git config --file=.gitmodules github-runner.url https://token:${{ steps.get-token.outputs.token }}@github.com/emisgroup/github-runner.git
          git submodule update --init --recursive
        env:
          GI_TOKEN: ${{ steps.get-token.outputs.token }}

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: eweblogs/terraform/
          framework: terraform

      - name: Destroy EWebLogs Infrastructure
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          ENVIRONMENT: ${{ vars.ENVIRONMENT }}
          GI_TOKEN: ${{ steps.get-token.outputs.token }}
          TF_VAR_gh_bearer_token: ${{ secrets.RUNNER_BEARER_TOKEN }}
        uses: ./github-runner/actions/terragrunt-destroy
        with:
          terraform-folder: "../eweblogs/terraform/"
          terragrunt-config: "./terragrunt.hcl"